# -*- coding: utf-8 -*-
"""SPAM MAIL _DETECTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMACs3G75h1laeJA0YeKPZt5ssTdyyjA
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df= pd.read_csv('mail_data.csv')

df.head()

data=df.where((pd.notnull(df)),'')

data.head()

data.loc  [data['Category']=='spam','Category',]=0
data.loc  [data['Category']=='ham','Category',]=1

X= data['Message']
Y=data['Category']

print(y)

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=3)

print(X.shape)
print(X_train.shape)
print(X_test.shape)

feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
X_train_features=feature_extraction.fit_transform(X_train)
X_test_features=feature_extraction.transform(X_test)
Y_train=Y_train.astype('int')
Y_test=Y_test.astype('int')

print(X_train_features)
print(X_test)

model=LogisticRegression()

model.fit(X_train_features,Y_train)

prediction_on_training_data=model.predict(X_train_features)
accuracy_on_training_data=accuracy_score(Y_train,prediction_on_training_data)

print('Accuracy on training data:',accuracy_on_training_data)

prediction_on_test_data=model.predict(X_test_features)
accuracy_on_test_data=accuracy_score(Y_test,prediction_on_test_data)

print('Accuracy on test data:',accuracy_on_test_data)

input=["Dear Intern This is a final reminder that the Labmentix Internship Orientation Session will begin in 15 minutes, at 11:30 AM today."]
prediction=model.predict(input_data_features)
print(prediction)
if(prediction[0]==1):
    print('Ham mail')
else:
    print('Spam mail')